### ISSUE TITLE
Leaking goroutines

### ISSUE THREAD

**Issue by evrardjp** [kubereboot/kured#1013]
This is unrelated to #1004, as this also appears in 1.16.0.

**Comment by evrardjp** [comment]
Apparently comes from our usage of logrus. Again, I got a branch fixing that, but I need to bring another solution that doesn't change the main loop. If anyone has a solution (I don't have much time to look at this rn), please feel free to propose a patch.

**Comment by jonaz** [comment]
It does not leak in 1.16.0 for us. We rolled back to that since .1 leaks both goroutines and memory:

here is a graph of go_goroutines{pod=~"kured.*"} showing the gooutine leak. The other issue already have memory graph. 

![Image](https://github.com/user-attachments/assets/b13897e3-369b-49b8-8e2d-347f7e1132d7)

**Comment by jonaz** [comment]
The leak is from every time NewCommand i called you leak goroutine in logrus.WriterLevel ![Image](https://github.com/user-attachments/assets/eee93316-4d70-4324-a0da-545af4824129)

**Comment by jonaz** [comment]
You want me to make a PR with the fix?

**Comment by evrardjp** [comment]
> The leak is from every time NewCommand is called you leak goroutine in logrus.WriterLevel ![Image](https://github.com/user-attachments/assets/eee93316-4d70-4324-a0da-545af4824129)
> 
> This might also be related to the memoryleak.

From my quick glance a few days ago, that's EXACTLY what I understood.
In my fork, I am replacing quite a few calls with slog. The refactor is a bit big, so I prefer NOT bringing this refactor in _as is_, and I prefer remplementing a fix.

I am fine with you committing a PR, it will get us to land this quicker, IMO. When do you think you can propose this? I am available for a bit in the next hours, which should be enough to fix this with your help.

In terms of the memory leak, my guess was that it's not _completely_ related. (The fact that we also append in the rebootAsRequired loop is crazy, and is also worth a fix).

Yet, IF the memory leak appeared in 1.16.1 (and a revert of 1.16.0 fixes the issue), this needs further investigation: Logrus didn't change. We changed go version and prom client. Go version could have an impact.
My guess is that we fix the goroutine leak first, then work on the rebootAsRequired (I would love a review if you're okay), then with thie cleaned up, we can find other big items.

Can you confirm that 1.16.0 is NOT having a memory leak for you @jonaz  ?

**Comment by jonaz** [comment]
@evrardjp yes 1.16.0 have no memory or goroutine leaks. It might be related to go version yes.

Looking at the code it's strange it ever worked.. should have leaked always. 

Im in CET timezone and can create PR tomorrow. We run kured on hundreds of vms so this impacted us a lot since we forgot limits on the deployment.

**Comment by evrardjp** [comment]
Sorry to hear that. 

I just arrived home, so i can push something real quick.
