### ISSUE TITLE
Move off of peter-evans/link-checker GH action

### ISSUE THREAD

**Issue by dholbach** [kubereboot/kured#308]
Move off of peter-evans/link-checker GH action, it's been replaced with https://github.com/lycheeverse/lychee-action

**Comment by jackfrancis** [comment]
It looks like lycheeverse/lychee-action doesn't support recursive usages (traversing into all child directories), see:

https://github.com/lycheeverse/lychee/issues/78

Since both kured workflows that use peter-evans/link-checker use its `-r` option (recursively search), should we wait until lycheeverse/lychee-action supports the recursive before making this change?

**Comment by dholbach** [comment]
Looks like https://github.com/lycheeverse/lychee/pull/165 is close, so we can wait until a fix is released. :-)

**Comment by evrardjp** [comment]
Update: Work not finished in lychee 165, maybe someone can help there? : )
