### ISSUE TITLE
Kured pods crash looping on clusters running Cilium Network plugin

### ISSUE THREAD

**Issue by sktemple** [kubereboot/kured#827]
The kured pods keep restarting on clusters running Cilium Network plugin. 
The logs show:
level=fatal msg="Error testing lock: timed out trying to get daemonset kured in namespace kured: Timed out trying to get daemonset kured in namespace kured: Get \"https://10.43.0.1:443/apis/apps/v1/namespaces/kured/daemonsets/kured\": dial tcp 10.43.0.1:443: i/o timeout"

They are installed with Helm Chart kured-5.2.0. The container image is ghcr.io/kubereboot/kured:1.14.0
Kubernetes Version is 1.27.4

**Note:** The clusters with kured pods running Calico are not having any issues.

**Comment by ckotzbauer** [comment]
Hi @sktemple,
is the cluster ready in general or are there any CNI issues? Do you have network-policies (or the cilium equivalents) applied? The kured pod can't reach your API-Server, this might be a configuration issue in your cluster rather than an issue in kured. I ran kured in my home-cluster with cilium for over 1,5 years without any issues.

**Comment by sktemple** [comment]
It was a network policy causing issue with Cilium but running fine with Calico - will need to look into it further to figure out why. 
Thanks @ckotzbauer
