### ISSUE TITLE
Kured should verify if node is still drained when delaying reboot

### ISSUE THREAD

**Issue by sebastiangaiser** [kubereboot/kured#929]
Hey, 

we had a problem with two controllers draining/uncordon nodes. To make the reboot more graceful, we configured `rebootDelay: 120s`. During these 2 mins the other controller uncordened the node. Kured rebooted the not drained node afterwards which is not optimal :D
So Kured should verify after the delay and right before the reboot is issued, if the node is still drained or not.

**Comment by jackfrancis** [comment]
I'm not sure there is a perfect solution for this. To a certain extent the "rebootDelay" functionality is unscientific: it makes no guarantees about outcomes after the delay. It seems this is generally well understood and folks use this feature as a "best-effort gesture" to better predict drain outcomes that may trail the immediate end of the drain process (though again, not guaranteed).

If there is another controller running on the system that observes cordoned nodes and uncordons them in response, then adding a follow-up drain gets us back to the original situation, where we may succeed in re-draining, but the workloads that are drained need a delay after in order to reboot gracefully; and now the other controller uncordons during that wait period; and so on and so on...

For this particular use case I think you want to disable that controller's power over kured-drained nodes (perhaps it can observe kured node annotations and skip uncordoning such nodes?), or consider not using this sleep option if there are multiple actors competing to cordon and uncordon nodes.

Are either of those options possible in your environment?

**Comment by sebastiangaiser** [comment]
The problem is definitely the other controller, not Kured. But despite the problem, how do you think about having this functionality as feature flag?

**Comment by evrardjp** [comment]
@sebastiangaiser  what do you think of the above?

**Comment by sebastiangaiser** [comment]
I'm also for the feature flag which (of course) can only be enabled when rebootDelay is greater than x
